### ISSUE TITLE
IPV6 config command syntax is not listed on the Evernode CLI page

### ISSUE THREAD

**Issue by effofexx** [EvernodeXRPL/evernode-docs#14]
It would be great if we could get the `evernode config instance ipv6` command added to the [Evernode CLI](https://github.com/EvernodeXRPL/evernode-docs/blob/main/docs/source/hosts/evernode-cli.md) page for quick reference.

Based on what we're seeing in the Evernode Community discord, a lot of new host operators are opting to skip IPV6 setup during installation, and then later wondering how to set it up afterwards.

Thanks

**Comment by BimsaraFernando** [comment]
This has been updated in the latest version of Evernode docs. Thanks.
